"""Auto: 2026-01-05 16:54

Revision ID: 6672af2766df
Revises: cb1bcd31ce65
Create Date: 2026-01-05 16:54:58.031503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6672af2766df'
down_revision: Union[str, None] = 'cb1bcd31ce65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niveis_acesso', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('niveis_acesso', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('niveis_acesso', 'permissoes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_unique_constraint(None, 'niveis_acesso', ['nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'niveis_acesso', type_='unique')
    op.alter_column('niveis_acesso', 'permissoes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('niveis_acesso', 'descricao',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('niveis_acesso', 'updated_at')
    # ### end Alembic commands ###
