"""Auto: 2026-01-05 16:04

Revision ID: cb1bcd31ce65
Revises: 2025_add_username
Create Date: 2026-01-05 16:04:02.396357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1bcd31ce65'
down_revision: Union[str, None] = '2025_add_username'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_casoteste_nome_projeto', 'casos_teste', ['projeto_id', 'nome'])
    op.alter_column('ciclos_teste', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uq_ciclo_nome_projeto', 'ciclos_teste', ['projeto_id', 'nome'])
    op.alter_column('metricas', 'nome_metrica',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('metricas', 'unidade_medida',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('metricas', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('modulos', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('modulos', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_unique_constraint('uq_modulo_por_sistema', 'modulos', ['sistema_id', 'nome'])
    op.create_unique_constraint('uq_passo_ordem', 'passos_caso_teste', ['caso_teste_id', 'ordem'])
    op.alter_column('projetos', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint('uq_projeto_por_modulo', 'projetos', ['modulo_id', 'nome'])
    op.alter_column('sistemas', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('sistemas', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_unique_constraint(None, 'sistemas', ['nome'])
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('usuarios', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'sistemas', type_='unique')
    op.alter_column('sistemas', 'descricao',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sistemas', 'nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint('uq_projeto_por_modulo', 'projetos', type_='unique')
    op.alter_column('projetos', 'nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint('uq_passo_ordem', 'passos_caso_teste', type_='unique')
    op.drop_constraint('uq_modulo_por_sistema', 'modulos', type_='unique')
    op.alter_column('modulos', 'descricao',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('modulos', 'nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('metricas', 'descricao',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metricas', 'unidade_medida',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('metricas', 'nome_metrica',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint('uq_ciclo_nome_projeto', 'ciclos_teste', type_='unique')
    op.alter_column('ciclos_teste', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_casoteste_nome_projeto', 'casos_teste', type_='unique')
    # ### end Alembic commands ###
